language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 70204ff5-1109-4a5a-bc2b-95a123876c50
  app: trello-testing
  on:
    repo: matteprg/trello-testing
